// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxGwTek9VJLxRIlO-nW6OPPVe1WMcGGYA',
    appId: '1:16413706714:android:47373880274e85892758e3',
    messagingSenderId: '16413706714',
    projectId: 'galactic-28694',
    storageBucket: 'galactic-28694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeF_Tz_c-CzHofZsGZXDiT3ho8w2yBhZA',
    appId: '1:16413706714:ios:2417b5106fdc39832758e3',
    messagingSenderId: '16413706714',
    projectId: 'galactic-28694',
    storageBucket: 'galactic-28694.appspot.com',
    androidClientId: '16413706714-d4h539vlq7hl9gs86bjmv2horqbnp93l.apps.googleusercontent.com',
    iosClientId: '16413706714-6p7rfuuu7hak2p9boq93ekr8uctd67p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
